# Generated by Django 6.0.3 on 2026-04-07 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('food_drinks', 'Food & Drinks'), ('experiences', 'Experiences'), ('discover', 'Discover'), ('wellness', 'Wellness'), ('transport', 'Transport'), ('addons', 'Add-ons'), ('specials', "Today's Specials")], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='owner_offerings/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for free or info-only items (e.g. Discover entries).', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, help_text="Optional. Used by Today's Specials to define the availability window.", null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_offerings', to=settings.AUTH_USER_MODEL)),
                ('properties', models.ManyToManyField(blank=True, help_text='Properties this offering is available for. Leave empty to keep it hidden from all guest apps.', related_name='owner_offerings', to='property_manager.property')),
            ],
            options={
                'verbose_name': 'Owner Offering',
                'verbose_name_plural': 'Owner Offerings',
                'ordering': ['section', 'order', 'name'],
            },
        ),
    ]
