# Generated by Django 6.0.3 on 2026-04-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0005_devicetoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='property_ma_booking_293868_idx',
            old_name='property_ma_booking_db2c74_idx',
        ),
    ]
