# Generated by Django 6.0.3 on 2026-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0006_rename_property_ma_booking_db2c74_idx_property_ma_booking_293868_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='linked_offerings',
            field=models.ManyToManyField(blank=True, help_text="Products from any section (Food & Drinks, Experiences, Discover, Wellness, Transport, Add-ons, Today's Specials) referenced by this notification.", related_name='notifications', to='property_manager.owneroffering'),
        ),
    ]
