# Generated by Django 6.0.3 on 2026-05-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0007_pushnotification_linked_offerings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerOfferingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='owner_offerings/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property_manager.owneroffering')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
